### PR TITLE
Check for 'end of string' when searching headline

### LINKED ISSUE #254: Refiling doesnt work when another headline starts with the same string
### Describe the bug

If you refile to a specific headline, but there is a headline above that headline that starts with the same text it will refile to it rather than the one you specify

### Steps to reproduce

1. Create 2 org files
2. In the 2nd org file create two headlines
3. Headline 1: "Start ajsijasigfajsija"
4. Headline 2: "Start"
5. Try to refile something from file 1 to 2 to the headline "Start"

### Expected behavior

I expect it to go to headline 2

### Emacs functionality

_No response_

### Minimal init.lua

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({})
  
  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[TSUpdate]]

  require('orgmode').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Screenshots and recordings

nvim-org-bug

### OS / Distro

Arch

### Neovim version/commit

0.7

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jgollenz**
fixes #254

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@jgollenz There is no easy way to write a test that is using prompts, which refiling does use. I would suggest to just create a test file, and call the code directly to assert if it returns what you expect.

File: tests/plenary/ui/mappings_spec.lua [hunk 1]
```diff
@@ -1568,4 +1568,28 @@ describe('Mappings', function()
...
+    })
+
+    local source_file = helpers.load_file_content({
+      '* to be refiled',
+      '* not to be refiled',
+    })
+
+    vim.fn.cursor(1, 1)
+    vim.cmd([[norm ,or]])
+    -- TODO: this is wrong, not a command. how to do the actual refiling?
```
Comment (TravonteD) [inline tests/plenary/ui/mappings_spec.lua:1586]: The function for this test is likely 
```lua
Capture:refile_to_headline()
```

File: tests/plenary/ui/mappings_spec.lua [hunk 2]
```diff
@@ -1568,4 +1568,28 @@ describe('Mappings', function()
...
+    vim.cmd([[exe "destination.org/foo\<CR>"]])
+    assert.are.same('* not to be refiled', vim.fn.getline(1))
+    -- TODO: how to switch to the destination file?
```
Comment (TravonteD) [inline tests/plenary/ui/mappings_spec.lua:1589]: you could use a fixture for the destination file and load it using `vim.cmd[[ edit <destfile> ]]` then from there use `vim.api.nvim_buf_get_lines` to get the list of lines to assert against

**Comment by jgollenz** [comment]
Thanks @TravonteD, I got it working :) however, I'm unsure if requiring `Files` is necessary here. I don't want to clutter the imports. What do you think @kristijanhusak?

**Comment by kristijanhusak** [comment]
@jgollenz it's ok to use whatever you need in the test.

File: tests/plenary/ui/mappings_spec.lua (hunk 1 above)
Comment (kristijanhusak) [reply tests/plenary/ui/mappings_spec.lua]: This works because Capture "class" doesn't have a lot of it's own internal state, but we should avoid calling these things directly. Capture is instantiated on the main Org class.
I just pushed a small change that can be used here like this:
```lua
require('orgmode').instance().capture:refile_to_headline()
```

File: tests/plenary/ui/mappings_spec.lua [hunk 3]
```diff
@@ -1568,4 +1570,29 @@ describe('Mappings', function()
...
+    })
+
+    local source_file = helpers.load_file_content({
+      '* to be refiled',
+      '* not to be refiled',
+    })
+
+    source_file = Files.get_current_file()
+    local item = source_file:get_closest_headline()
+    Capture:refile_to_headline(destination_file, source_file:get_headline_lines(item), item, 'foo')
```
Comment (kristijanhusak) [inline tests/plenary/ui/mappings_spec.lua:1588]:
```suggestion
    local org = require('orgmode') -- you can move this up outside of tests
    org.instance().capture:refile_to_headline(destination_file, source_file:get_headline_lines(item), item, 'foo')
```

Comment (jgollenz) [reply tests/plenary/ui/mappings_spec.lua:1588]: When I add this change, `instance` is a nil value field (which is also not callable, but removing the parenthesis makes no difference, still nil)

Comment (kristijanhusak) [reply tests/plenary/ui/mappings_spec.lua:1588]: You need to rebase from master branch. I added `instance()` function recently.

Comment (jgollenz) [reply tests/plenary/ui/mappings_spec.lua]: Thanks, fixed it

File: lua/orgmode/parser/file.lua [hunk 4]
```diff
@@ -204,7 +204,7 @@ end
 ---@return Section[]
 function File:find_headlines_by_title(title)
```
Comment (kristijanhusak) [inline lua/orgmode/parser/file.lua:205]: I just figured out that this method is also used for autocompletion, which should actually do matching only by the beginning of the string. Let's add a second argument called `strict` which would default to true, and do matching as it is done now. If `strict` is false, do it the old way.
Once that's added, just pass `false` [here](https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/org/hyperlinks.lua#L70).
Another option, maybe even a bit cleaner, is to introduce a method called `File:find_headlines_matching_title` that would behave in the old way, and use that in hyperlinks autocompletion.

Comment (jgollenz) [reply lua/orgmode/parser/file.lua:205]: I'd prefer the version where we pass a second argument, as I'd rather reduce than increase the amount of functions we have. Also `exact` would be better than `strict` in my opinion. Just let me know which you want to settle on.

Comment (kristijanhusak) [reply lua/orgmode/parser/file.lua:205]: Sure that works. Exact is better than strict.

Comment (jgollenz) [reply lua/orgmode/parser/file.lua:205]: What about here: https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/org/hyperlinks.lua#L106 ?

Comment (kristijanhusak) [reply lua/orgmode/parser/file.lua:205]: There we don't need strict matching, just start needs to match.

Comment (jgollenz) [reply lua/orgmode/parser/file.lua]: @kristijanhusak pushed some changes, should be working now

**Review by kristijanhusak — APPROVED** [review]
Looks good, thanks!
