### PR TITLE
Agenda help improvements

### LINKED ISSUE #445: `g?` shows the same mappings for every agenda view
### Describe the bug

Mappings like `f - Go forward one span` are displayed in views that don't have spans (search, match tags, ...)

### Steps to reproduce

Open any agenda view that is not the actual agenda (list tags, search, match tags) and type `g?` to open the help

### Expected behavior

Only the key-mappings that are actually applicable to that view should be displayed

### Emacs functionality

-

### Minimal init.lua

scripts/minimal_init.lua

### Screenshots and recordings

_No response_

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jgollenz**
closes #445 

I chose to just use `vim.b.org_agenda_type` after all, as it was easier than passing it through with `opts`. If it is obfuscating the logic too much, let me know

### CODE REVIEW

File: lua/orgmode/objects/help.lua [hunk 1]
```diff
@@ -201,7 +205,18 @@ function Help._prepare_orgagenda(mappings, max_height)
   end
 
   local content = { string.format(' **Orgmode mappings - Agenda%s:**', scroll_more_text), '' }
-  for _, item in ipairs(helps.orgagenda) do
+  if vim.b.org_agenda_type == 'agenda' then
```
Comment (kristijanhusak) [inline lua/orgmode/objects/help.lua:208]: Since `for` block is actually the same as for `generic` mappings, we can just merge both generic and agenda specific into one, and let the "generic" loop handle everything. Something like this:

```lua
-- Copy to make sure we do not override any references
local mappings = vim.deepcopy(helps.orgagenda.generic)
if vim.b.org_agenda_type == 'agenda' then
  mappings = utils.concat(helps.orgagenda.agenda_specific, mappings)
end

for _, item in ipairs(mappings) do
  -- ...
endfor
```

Comment (jgollenz) [reply lua/orgmode/objects/help.lua:208]: Great idea :)

Comment (kristijanhusak) [reply lua/orgmode/objects/help.lua:208]: Note that I forgot to copy "agenda_specific" mappings, since `utils.concat` will mutate it.

Comment (jgollenz) [reply lua/orgmode/objects/help.lua:212]: Should be fixed. Also made some changes regarding the replacement of `<prefix>` with the actual prefix from the config.
